// Do not edit this file directly.
// These values are sourced from the .env file.
// See the .env file for the full configuration.

export const firebaseConfig = {
  apiKey: "AIzaSyATnl_6_0CGoMZ1II_fXmr25eHpBeswBTw",
  authDomain: "fsfa-tl5x4.firebaseapp.com",
  projectId: "fsfa-tl5x4",
  storageBucket: "fsfa-tl5x4.appspot.com",
  messagingSenderId: "546156811876",
  appId: "1:546156811876:web:fd69c51b9ce24ef3b77171",
  measurementId: ""
};
